In [1]:
from PrepareData.gen_doc_vec import LsiVec, LdaVec, Doc2vecVec

In [22]:
texts = [['human', 'interface', 'computer'],
             ['survey', 'user', 'computer', 'system', 'response', 'time'],
             ['eps', 'user', 'interface', 'system'],
             ['system', 'human', 'system', 'eps'],
             ['user', 'response', 'time'],
             ['trees'],
             ['graph', 'trees'],
             ['graph', 'minors', 'trees'],
             ['graph', 'minors', 'survey']]

In [48]:
from gensim.models.doc2vec import TaggedDocument, Doc2Vec
import numpy as np
import random

In [49]:
docs = [TaggedDocument(d, [i]) for i, d in enumerate(texts)]

In [54]:
def train(doc ,size = 300, min_count=2, batch_size = 10000, epoch_num=10):
    model = Doc2Vec(size=size, min_count=min_count)
    model.build_vocab(docs)
    model.train(docs, total_examples=model.corpus_count, epochs=epoch_num)

    return model

In [55]:
model = train(docs)

In [60]:
import pandas as pd
pd.DataFrame(list(model.docvecs))

0         1         2         3         4         5         6    \
0 -0.000914  0.000619  0.001010  0.001431 -0.000639 -0.000989  0.000366   
1 -0.000824 -0.000410 -0.001515  0.001547  0.000038  0.001260  0.000346   
2  0.001271 -0.000484 -0.001058 -0.001345 -0.000678  0.000965  0.000781   
3 -0.000045 -0.000103 -0.000805 -0.000557 -0.001264  0.000735 -0.000989   
4 -0.000348  0.001531 -0.000448 -0.001422  0.001547  0.000517  0.001585   
5 -0.000354 -0.000386 -0.001418 -0.000359 -0.000291 -0.000615  0.000201   
6  0.000898  0.001591  0.000483 -0.001514 -0.000270  0.001008  0.000785   
7  0.000940 -0.000602  0.000687 -0.001243 -0.000029 -0.000870  0.000869   
8 -0.001349 -0.000279  0.001470  0.000551 -0.000456 -0.000568 -0.000854   

        7         8         9      ...          290       291       292  \
0  0.001659 -0.000193 -0.000714    ...    -0.000396 -0.000371 -0.000418   
1  0.001526  0.000491 -0.000078    ...    -0.001132 -0.000810 -0.000203   
2 -0.000067  0.001501  0.000461    ...     0.000178  0.000987 -0.000242   
3 -0.001609  0.001369  0.000728    ...     0.001472  0.001668 -0.000175   
4 -0.001267  0.001017 -0.000874    ...     0.001379  0.001435 -0.000235   
5  0.000311  0.000041 -0.000780    ...     0.000577 -0.001010 -0.001531   
6 -0.001291 -0.000525  0.000973    ...     0.000167  0.000054  0.000730   
7  0.000914  0.000906 -0.000164    ...     0.001084 -0.001247 -0.001324   
8  0.000949  0.001047 -0.001016    ...    -0.001652  0.000081 -0.001177   

        293       294       295       296       297       298       299  
0 -0.000472  0.000529 -0.001511  0.001557 -0.000518 -0.000108  0.001144  
1 -0.001210 -0.001118 -0.000247  0.000596  0.000960  0.000785 -0.001516  
2 -0.000753  0.000938  0.001351  0.001539  0.001079 -0.000323  0.000608  
3 -0.000222 -0.001042 -0.001158  0.000911 -0.000739  0.000907  0.000938  
4  0.000395 -0.000969  0.001650 -0.000314  0.000284  0.000414  0.000154  
5 -0.000062 -0.000810  0.000685 -0.000885 -0.000760  0.000872 -0.001388  
6  0.001238  0.001497 -0.001592  0.001623 -0.001053  0.000128  0.000637  
7 -0.000655  0.001106 -0.001001 -0.000396 -0.000869 -0.001090  0.001580  
8 -0.001379 -0.000278  0.000840  0.000879  0.001341 -0.001349 -0.000862  

[9 rows x 300 columns]

In [63]:
inferred_vector = model.infer_vector(['human', 'interface', 'computer'])

In [64]:
sims = model.docvecs.most_similar([inferred_vector], topn=len(model.docvecs))

In [66]:
for docid, sim in sims:
    print(docid, sim)

6 0.12664923071861267
1 0.05558818206191063
2 0.05066130310297012
0 0.04422065615653992
3 0.019098464399576187
8 0.016263242810964584
5 -0.037140462547540665
4 -0.0634060725569725
7 -0.12276961654424667


In [71]:
l = [1,2,3,4,5,6,7,8,9,]
l[1:20]

[2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
# lv = LsiVec(10)

In [20]:
# lv.fit(texts, 'tmp1', use_exist_dictionary=True)

In [21]:
# lv.get_topic_vec()

In [16]:
# ld = LdaVec(20)

In [17]:
# ld.fit(texts, 'tmp1', use_exist_dictionary=True)

In [18]:
# ld.get_topic_vec()

In [9]:
d2v = Doc2vecVec(30)

In [10]:
d2v.fit(texts, 'tmp1')

In [11]:
d2v.get_topic_vec()

0         1         2         3         4         5         6   \
0 -0.009106  0.006196  0.010123  0.014266 -0.006340 -0.009890  0.003661   
1 -0.008221 -0.004084 -0.015170  0.015464  0.000443  0.012610  0.003425   
2  0.012707 -0.004831 -0.010553 -0.013447 -0.006744  0.009619  0.007772   
3 -0.000432 -0.001048 -0.008058 -0.005568 -0.012602  0.007353 -0.009882   
4 -0.003513  0.015310 -0.004471 -0.014182  0.015472  0.005150  0.015849   
5 -0.003541 -0.003866 -0.014187 -0.003591 -0.002920 -0.006146  0.002012   
6  0.008979  0.015915  0.004835 -0.015137 -0.002698  0.010071  0.007850   
7  0.009394 -0.006029  0.006854 -0.012440 -0.000287 -0.008696  0.008673   
8 -0.013483 -0.002780  0.014724  0.005493 -0.004544 -0.005696 -0.008552   

         7         8         9     ...           20        21        22  \
0  0.016557 -0.001955 -0.007129    ...    -0.013501  0.006008  0.002255   
1  0.015221  0.004851 -0.000767    ...    -0.002744  0.006696 -0.010067   
2 -0.000679  0.014951  0.004584    ...     0.007742 -0.008776  0.011964   
3 -0.016075  0.013675  0.007269    ...    -0.015185 -0.001239 -0.015690   
4 -0.012646  0.010154 -0.008760    ...    -0.012802 -0.005856  0.004916   
5  0.003117  0.000423 -0.007797    ...     0.016573 -0.010503 -0.000343   
6 -0.012903 -0.005257  0.009729    ...     0.007555 -0.012012 -0.001302   
7  0.009116  0.009067 -0.001640    ...     0.007374 -0.007284  0.010430   
8  0.009466  0.010431 -0.010157    ...     0.004484 -0.012807  0.016488   

         23        24        25        26        27        28        29  
0 -0.004077  0.015388 -0.016314  0.002266  0.016337 -0.005062  0.007643  
1  0.007752  0.003353 -0.001648  0.010607 -0.011103 -0.008836 -0.008161  
2  0.013094 -0.005966  0.004010  0.012651 -0.003182 -0.011516 -0.013630  
3  0.001301 -0.008242  0.010377  0.010955  0.006891 -0.002377 -0.011577  
4  0.010149  0.008583 -0.006471  0.005934  0.013015 -0.012909  0.011083  
5 -0.013800 -0.004803 -0.012885  0.003980 -0.016198  0.012337  0.000015  
6  0.007528  0.004761  0.007803 -0.003541 -0.013467  0.008138  0.014776  
7 -0.015919  0.008640 -0.004620 -0.009229 -0.013425  0.009339 -0.001649  
8 -0.006890  0.006323 -0.012484 -0.012193 -0.004053 -0.015372  0.009278  

[9 rows x 30 columns]

In [12]:
test = ['graph', 'minors']

In [13]:
lv.infer_vec(test)

array([[ 0.641566  , -0.06849104,  0.10875107,  0.6002956 ,  0.06639508,
         0.1776531 ,  0.35045627, -0.12437793,  0.19303381]],
      dtype=float32)

In [14]:
ld.infer_vec(test)

array([[0.02085629, 0.02085629, 0.60373056, 0.02085629, 0.02085629,
        0.02085629, 0.02085629, 0.02085629, 0.02085629, 0.02085629,
        0.02085629, 0.02085629, 0.02085629, 0.02085629, 0.02085629,
        0.02085629, 0.02085629, 0.02085629, 0.02085629, 0.02085629]],
      dtype=float32)

In [15]:
d2v.infer_vec(test)

array([[ 0.00745902, -0.01259371, -0.00073123,  0.01499203, -0.01296325,
        -0.01373851,  0.01591635,  0.01121232, -0.00123844,  0.00901498,
         0.01097143, -0.01384251,  0.00059627,  0.01495396,  0.00940856,
         0.00446643,  0.00301305, -0.00557913, -0.00499088, -0.01028442,
         0.00844601, -0.01138198,  0.00725462, -0.00751661,  0.00935785,
        -0.01572627,  0.00611854, -0.00710991,  0.01048621,  0.01365955]],
      dtype=float32)

In [76]:
import pickle

with open('key-to-content', 'rb') as fp:
    data = pickle.load(fp)
data

{'《最高人民法院审理离婚案件子女抚养问题的若干意见》第一条': {'content': '两周岁以下的子女，一般随母方生活。母方有下列情形之一的，可随父方生活:（1）患有久治不愈的传染性疾病或其他严重疾病，子女不宜与其共同生活的；（2）有抚养条件不尽抚养义务，而父方要求子女随其生活的；（3）因其他原因，子女确无法随母方生活的。\r',
  'fomalname': '《关于人民法院审理离婚案件处理子女抚养问题的若干具体意见》',
  'num': '第一条'},
 '最高人民院关于适用《中华人民共和国婚姻法》若干问题的解释（二）第十条': {'content': '当事人请求返还按照习俗给付的彩礼的，如果查明属于以下情形，人民法院应当予以支持：（一）双方未办理结婚登记手续的；（二）双方办理结婚登记手续但确未共同生活的；（三）婚前给付并导致给付人生活困难的。适用前款第（二）、（三）项的规定，应当以双方离婚为条件。',
  'fomalname': '关于适用《中华人民共和国婚姻法》若干问题的解释（二）',
  'num': '第十条'},
 '《最高人民法院关于适用﹤中华人民共和国婚姻法﹥若干问题的解释（三）》第五条': {'content': '夫妻一方个人财产在婚后产生的收益，除孳息和自然增值外，应认定为夫妻共同财产。',
  'fomalname': '关于适用《中华人民共和国婚姻法》若干问题的解释（一）',
  'num': '第五条'},
 '《最高人民法院关于适用若干问题的解释（一）》第五条': {'content': '夫妻一方个人财产在婚后产生的收益，除孳息和自然增值外，应认定为夫妻共同财产。',
  'fomalname': '关于适用《中华人民共和国婚姻法》若干问题的解释（一）',
  'num': '第五条'},
 '《中华人民共和国婚姻法（2001年）》第三十二条': {'content': '男女一方要求离婚的，可由有关部门进行调解或直接向人民法院提出离婚诉讼。人民法院审理离婚案件，应当进行调解；如感情确已破裂，调解无效，应准予离婚。有下列情形之一，调解无效的，应准予离婚：（一）重婚或有配偶者与他人同居的；（二）实施家庭暴力或虐待、遗弃家庭成员的；（三）有赌博、吸毒等恶习屡教不改的；（四）因感情不和分居满二年的；（五）其他导致夫妻感情破裂的

In [79]:
res = []
for k,v in data.items():
    res.append(v['fomalname'])

In [81]:
set(res)

{'《《&lt法》',
 '《上海市实施〈中华人民共和国妇女权益保障法〉办法》',
 '《中华人民共和国侵权责任法》',
 '《中华人民共和国农村土地承包法》',
 '《中华人民共和国合同法》',
 '《中华人民共和国妇女儿童权益保护法》',
 '《中华人民共和国妇女权益保障法》',
 '《中华人民共和国婚姻法》',
 '《中华人民共和国担保法》',
 '《中华人民共和国收养法》',
 '《中华人民共和国未成年人保护法》',
 '《中华人民共和国民事诉讼法》',
 '《中华人民共和国民法通则》',
 '《中华人民共和国涉外民事关系法律适用法》',
 '《中华人民共和国涉外民事关系适用法》',
 '《中华人民共和国物权法》',
 '《关于人民法院审理未办结婚登记而以夫妻名义同居生活案件的若干意见》',
 '《关于人民法院审理离婚案件处理子女抚养问题的若干具体意见》',
 '《关于人民法院审理离婚案件处理财产分割问题的若干具体意见》',
 '《关于人民法院审理离婚案件如何认定夫妻感情确以破裂的若干具体意见》',
 '《关于民事诉讼证据的若干规定》',
 '《关于贯彻执行民事政策法律若干问题的意见》',
 '《婚姻登记管理条例》',
 '《广西壮族自治区人口和计划生育条例》',
 '《最高人民法院〈关于执行程序中计算迟延履行期间的债务利息适用法律若干问题的解释〉》',
 '《最高人民法院关于人民法院认可台湾地区有关法院民事判决的规定》',
 '《最高人民法院关于以法院专递方式邮寄送达民事诉讼文书的若干规定》',
 '《最高人民法院关于审理涉台民商事案件法律适用问题的规定》',
 '《最高人民法院关于涉港澳民商案件司法文书送达问题若干规定》',
 '《最高人民法院关于调整高级人民法院和中级人民法院管辖一审民商事案件标准的通知》',
 '《最高人民法院关于贯彻执行民事政策法律若干问题的意见》',
 '《诉讼费用交纳办法》',
 '关于贯彻执行《中华人民共和国民法通则》若干问题的意见（试行）',
 '关于适用《中华人民共和国婚姻法》若干问题的解释（一）',
 '关于适用《中华人民共和国婚姻法》若干问题的解释（二）',
 '关于适用《中华人民共和国民事诉讼法》的解释',
 '关于适用《中华人民共和国民事诉讼法》若干问题的意见',
 '最高人民法院《关于人民法院审理借贷案件的若干意

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/statute_code.csv')
data

code                  name                       tree
0    9000           民事案由（2011版）                      9000-
1    9001                 人格权纠纷                 9001-9000-
2    9002                 人格权纠纷            9002-9001-9000-
3    9003         生命权、健康权、身体权纠纷       9003-9002-9001-9000-
4    9004                 姓名权纠纷       9004-9002-9001-9000-
5    9005                 肖像权纠纷       9005-9002-9001-9000-
6    9006                 名誉权纠纷       9006-9002-9001-9000-
7    9007                 荣誉权纠纷       9007-9002-9001-9000-
8    9008                 隐私权纠纷       9008-9002-9001-9000-
9    9009               婚姻自主权纠纷       9009-9002-9001-9000-
10   9010               人身自由权纠纷       9010-9002-9001-9000-
11   9011               一般人格权纠纷       9011-9002-9001-9000-
12   9012             婚姻家庭、继承纠纷                 9012-9000-
13   9013                婚姻家庭纠纷            9013-9012-9000-
14   9014                婚约财产纠纷       9014-9013-9012-9000-
15   9015                  离婚纠纷       9015-9013-9012-9000-
16   9016               离婚后财产纠纷       9016-9013-9012-9000-
17   9017             离婚后损害责任纠纷       9017-9013-9012-9000-
18   9018                婚姻无效纠纷       9018-9013-9012-9000-
19   9019                撤销婚姻纠纷       9019-9013-9012-9000-
20   9020              夫妻财产约定纠纷       9020-9013-9012-9000-
21   9021                同居关系纠纷       9021-9013-9012-9000-
22   9022              同居关系析产纠纷  9022-9021-9013-9012-9000-
23   9023            同居关系子女抚养纠纷  9023-9021-9013-9012-9000-
24   9024                  抚养纠纷       9024-9013-9012-9000-
25   9025                 抚养费纠纷  9025-9024-9013-9012-9000-
26   9026              变更抚养关系纠纷  9026-9024-9013-9012-9000-
27   9027                  扶养纠纷       9027-9013-9012-9000-
28   9028                 扶养费纠纷  9028-9027-9013-9012-9000-
29   9029              变更扶养关系纠纷  9029-9027-9013-9012-9000-
..    ...                   ...                        ...
831  9831          申请执行知识产权仲裁裁决       9831-9829-9771-9000-
832  9832            申请执行涉外仲裁裁决       9832-9829-9771-9000-
833  9833  申请认可和执行香港特别行政区法院民事判决       9833-9829-9771-9000-
834  9834    申请认可和执行香港特别行政区仲裁裁决       9834-9829-9771-9000-
835  9835  申请认可和执行澳门特别行政区法院民事判决       9835-9829-9771-9000-
836  9836    申请认可和执行澳门特别行政区仲裁裁决       9836-9829-9771-9000-
837  9837     申请认可和执行台湾地区法院民事判决       9837-9829-9771-9000-
838  9838       申请认可和执行台湾地区仲裁裁决       9838-9829-9771-9000-
839  9839    申请承认和执行外国法院民事判决、裁定       9839-9829-9771-9000-
840  9840         申请承认和执行外国仲裁裁决       9840-9829-9771-9000-
841  9841                执行异议之诉            9841-9771-9000-
842  9842             案外人执行异议之诉       9842-9841-9771-9000-
843  9843           申请执行人执行异议之诉       9843-9841-9771-9000-
844  9844            执行分配方案异议之诉       9844-9841-9771-9000-
845  9845          申请确认人民调解协议效力  9845-9294-9131-9130-9000-
846  9846            申请撤销调解确认决定  9846-9294-9131-9130-9000-
847  9847                 撤销支付令       9847-9794-9771-9000-
848  9848                 生命权纠纷  9848-9003-9002-9001-9000-
849  9849                 健康权纠纷  9849-9003-9002-9001-9000-
850  9850                 身体权纠纷  9850-9003-9002-9001-9000-
851  9851         协助送达司法文书和调查取证            9851-9771-9000-
852  9852       协助香港特别行政区送达司法文书       9852-9851-9771-9000-
853  9853         协助香港特别行政区调查取证       9853-9851-9771-9000-
854  9854       协助澳门特别行政区送达司法文书       9854-9851-9771-9000-
855  9855         协助澳门特别行政区调查取证       9855-9851-9771-9000-
856  9856          协助台湾地区送达司法文书       9856-9851-9771-9000-
857  9857            协助台湾地区调查取证       9857-9851-9771-9000-
858  9858            协助外国送达司法文书       9858-9851-9771-9000-
859  9859              协助外国调查取证       9859-9851-9771-9000-
860  9860            申请实现担保物权案件            9860-9771-9000-

[861 rows x 3 columns]

In [ ]:
import re
level = re.compile(r'(\d{4})-9130-9000')
def code_helper(x):
    tmp = level.search(x)
    if tmp:
        return tmp.group(1)
    else:
        return None

In [24]:
data[data['code']==9015]

code  name                  tree
15  9015  离婚纠纷  9015-9013-9012-9000-

In [18]:
d = {
    '案由代码' : [9001, 9012, 9047, 9130, 9299, 9461, 9483, 9542, 9705, 9771],
    '案由' : ['人格权纠纷', '婚姻家庭、继承纠纷', '物权纠纷', '合同、无因管理、不当得利纠纷', '知识产权与竞争纠纷',
           '劳动争议、人事争议', '海事海商纠纷', '与公司、证券、保险、票据等有关的民事纠纷', '侵权责任纠纷', '适用特殊程序案件案由'],
    '案件数量' : [89028, 750815, 115028, 2331551, 32123, 173933, 3171, 66999, 590498, 1786]
}

d = pd.DataFrame(d, columns=['案由代码', '案由', '案件数量'])
d

案由代码                    案由     案件数量
0  9001                 人格权纠纷    89028
1  9012             婚姻家庭、继承纠纷   750815
2  9047                  物权纠纷   115028
3  9130        合同、无因管理、不当得利纠纷  2331551
4  9299             知识产权与竞争纠纷    32123
5  9461             劳动争议、人事争议   173933
6  9483                海事海商纠纷     3171
7  9542  与公司、证券、保险、票据等有关的民事纠纷    66999
8  9705                侵权责任纠纷   590498
9  9771            适用特殊程序案件案由     1786

In [23]:
data[data['name'] == '继承纠纷']  
#9131 9297 9295
#9013 9039

code  name             tree
39  9039  继承纠纷  9039-9012-9000-

In [1]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer

In [15]:

corpus=["I come to China to travel",
    "This is a car polupar in China",
    "I love tea and Apple ",
    "The work is to write some papers in science"]

vectorizer = CountVectorizer()
count = vectorizer.fit_transform(corpus)
wb = vectorizer.get_feature_names()
print(wb)

['and', 'apple', 'car', 'china', 'come', 'in', 'is', 'love', 'papers', 'polupar', 'science', 'some', 'tea', 'the', 'this', 'to', 'travel', 'work', 'write']


In [16]:
tfidf = TfidfTransformer()
res = tfidf.fit_transform(count)
print(res)

  (0, 4)	0.4424621378947393
  (0, 15)	0.697684463383976
  (0, 3)	0.348842231691988
  (0, 16)	0.4424621378947393
  (1, 3)	0.3574550433419527
  (1, 14)	0.45338639737285463
  (1, 6)	0.3574550433419527
  (1, 2)	0.45338639737285463
  (1, 9)	0.45338639737285463
  (1, 5)	0.3574550433419527
  (2, 7)	0.5
  (2, 12)	0.5
  (2, 0)	0.5
  (2, 1)	0.5
  (3, 15)	0.2811316284405006
  (3, 6)	0.2811316284405006
  (3, 5)	0.2811316284405006
  (3, 13)	0.3565798233381452
  (3, 17)	0.3565798233381452
  (3, 18)	0.3565798233381452
  (3, 11)	0.3565798233381452
  (3, 8)	0.3565798233381452
  (3, 10)	0.3565798233381452


/Users/wangxiao/.pyenv/versions/3.5.3/lib/python3.5/site-packages/sklearn/feature_extraction/text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [17]:
type(res)

scipy.sparse.csr.csr_matrix

In [18]:
res.indices

array([ 4, 15,  3, 16,  3, 14,  6,  2,  9,  5,  7, 12,  0,  1, 15,  6,  5,
       13, 17, 18, 11,  8, 10], dtype=int32)

In [19]:
res.data

array([0.44246214, 0.69768446, 0.34884223, 0.44246214, 0.35745504,
       0.4533864 , 0.35745504, 0.4533864 , 0.4533864 , 0.35745504,
       0.5       , 0.5       , 0.5       , 0.5       , 0.28113163,
       0.28113163, 0.28113163, 0.35657982, 0.35657982, 0.35657982,
       0.35657982, 0.35657982, 0.35657982])

In [20]:
tag = list(res.indptr)
tag[:-1]

[0, 4, 10, 14]

In [27]:
dic = {
    'word' : [],
    'doc' : [],
    'tfidf' : [],
}

tag = list(res.indptr)[1:-1]
index = 0
doc_index = 0
for word_index, tfidf in zip(res.indices, res.data):
    if len(tag)>0 and index == tag[0]:
        tag.pop(0)
        doc_index += 1
    dic['word'].append(word_index)
    dic['doc'].append(doc_index)
    dic['tfidf'].append(tfidf)
    index += 1

In [28]:
import pandas as pd
df = pd.DataFrame(dic)
df

doc     tfidf  word
0     0  0.442462     4
1     0  0.697684    15
2     0  0.348842     3
3     0  0.442462    16
4     1  0.357455     3
5     1  0.453386    14
6     1  0.357455     6
7     1  0.453386     2
8     1  0.453386     9
9     1  0.357455     5
10    2  0.500000     7
11    2  0.500000    12
12    2  0.500000     0
13    2  0.500000     1
14    3  0.281132    15
15    3  0.281132     6
16    3  0.281132     5
17    3  0.356580    13
18    3  0.356580    17
19    3  0.356580    18
20    3  0.356580    11
21    3  0.356580     8
22    3  0.356580    10

In [31]:
for word, group in df.groupby('word'):
    tmp = group.sort_values(by="tfidf",ascending= False)
    print({
        "word": word,
        "doc_tfidf": [{'doc':doc, 'tfidf':tfidf} for doc, tfidf in zip(tmp['doc'].tolist(), tmp['tfidf'].tolist())]
    })

{'doc_tfidf': [{'doc': 2, 'tfidf': 0.5}], 'word': 0}
{'doc_tfidf': [{'doc': 2, 'tfidf': 0.5}], 'word': 1}
{'doc_tfidf': [{'doc': 1, 'tfidf': 0.45338639737285463}], 'word': 2}
{'doc_tfidf': [{'doc': 1, 'tfidf': 0.3574550433419527}, {'doc': 0, 'tfidf': 0.348842231691988}], 'word': 3}
{'doc_tfidf': [{'doc': 0, 'tfidf': 0.4424621378947393}], 'word': 4}
{'doc_tfidf': [{'doc': 1, 'tfidf': 0.3574550433419527}, {'doc': 3, 'tfidf': 0.2811316284405006}], 'word': 5}
{'doc_tfidf': [{'doc': 1, 'tfidf': 0.3574550433419527}, {'doc': 3, 'tfidf': 0.2811316284405006}], 'word': 6}
{'doc_tfidf': [{'doc': 2, 'tfidf': 0.5}], 'word': 7}
{'doc_tfidf': [{'doc': 3, 'tfidf': 0.3565798233381452}], 'word': 8}
{'doc_tfidf': [{'doc': 1, 'tfidf': 0.45338639737285463}], 'word': 9}
{'doc_tfidf': [{'doc': 3, 'tfidf': 0.3565798233381452}], 'word': 10}
{'doc_tfidf': [{'doc': 3, 'tfidf': 0.3565798233381452}], 'word': 11}
{'doc_tfidf': [{'doc': 2, 'tfidf': 0.5}], 'word': 12}
{'doc_tfidf': [{'doc': 3, 'tfidf': 0.356579823338